# This is a config for E2B sandbox template.
# You can use template ID (ue636jo3bbcv7pe7dq8c) or template name (creator-nextjs-t-2) to create a sandbox:

# Python SDK
# from e2b import Sandbox, AsyncSandbox
# sandbox = Sandbox("creator-nextjs-t-2") # Sync sandbox
# sandbox = await AsyncSandbox.create("creator-nextjs-t-2") # Async sandbox

# JS SDK
# import { Sandbox } from 'e2b'
# const sandbox = await Sandbox.create('creator-nextjs-t-2')

team_id = "084678e4-8b76-4a71-a0c9-1a0448c05b0e"
start_cmd = "/compile_page.sh"
dockerfile = "e2b.Dockerfile"
template_name = "creator-nextjs-t-2"
template_id = "ue636jo3bbcv7pe7dq8c"
